CREATE TABLE TBContato
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,

    Nome NVARCHAR(100) NOT NULL,

    Email NVARCHAR(100) NOT NULL,

    Telefone NVARCHAR(20) NOT NULL,

    Cargo NVARCHAR(100) NULL,

    Empresa NVARCHAR(100) NULL
);
GO

CREATE UNIQUE INDEX IX_TBContato_Email
ON TBContato(Email);
GO

CREATE UNIQUE INDEX IX_TBContato_Telefone
ON TBContato(Telefone);
GO