CREATE TABLE TBDespesa
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,

    Descricao NVARCHAR(100) NOT NULL,

    DataOcorrencia DATETIME2 NOT NULL,

    Valor DECIMAL(18,2) NOT NULL,

    FormaPagamento INT NOT NULL
);
GO